export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DECREMENT_IN_CART = "DECREMENT_IN_CART";
export const SET_SHIPPING = "SET_SHIPPING";

export const CHECKOUT_INITIALISE = "CHECKOUT_INITIALISE";
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";
export const LOADING_CHECKOUT = "LOADING_CHECKOUT";

export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const RECEIVE_VIDEOS = "RECEIVE_VIDEOS";

export const SHOWN_INTRO_SLIDE = "SHOWN_INTRO_SLIDE";
