//CART ACTIONS
type CART_ACTIONS =
  | ADD_TO_CART
  | REMOVE_FROM_CART
  | DECREMENT_IN_CART
  | SET_SHIPPING;

type ADD_TO_CART = "ADD_TO_CART";
type REMOVE_FROM_CART = "REMOVE_FROM_CART";
type DECREMENT_IN_CART = "DECREMENT_IN_CART";
type SET_SHIPPING = "SET_SHIPPING";

type PRODUCTS_ACTIONS = RECEIVE_PRODUCTS | ADD_TO_CART | REMOVE_FROM_CART;

//CHECKOUT ACTIONS
type CHECKOUT_ACTIONS =
  | CHECKOUT_INITIALISE
  | CHECKOUT_REQUEST
  | CHECKOUT_SUCCESS
  | CHECKOUT_FAILURE
  | LOADING_CHECKOUT;

type CHECKOUT_INITIALISE = "CHECKOUT_INITIALISE";
type CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
type CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
type CHECKOUT_FAILURE = "CHECKOUT_FAILURE";
type LOADING_CHECKOUT = "LOADING_CHECKOUT";

//DATA ACTIONS

type DATA_ACTIONS = RECEIVE_PRODUCTS | RECEIVE_VIDEOS;

type RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
type RECEIVE_VIDEOS = "RECEIVE_VIDEOS";

type SHOWN_INTRO_SLIDE = "SHOWN_INTRO_SLIDE";
