# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses:
          actions/checkout@v2
          # does an install
      - name: Run install
        run: yarn install
      - name: run typecheck
        run: yarn run typecheck
      - name: set percy token
        run: export PERCY_TOKEN=${{ secrets.PERCY_TOKEN }}
      - name: run e2e tests
        run: yarn ci
